---
- hosts: all
  sudo: true
  tasks:
   - name: install apache2
     apt: name=apache2 update_cache=yes state=latest
   - name: install python-virtualenv
     apt: name=python-virtualenv update_cache=yes state=latest
     notify:
     - restart apache2
   - name: ensure apache is running (and enable it at boot)
     service: name=apache2 state=started enabled=yes
  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted
   
# notify:
#      - install pip
#  handlers:
#   - name: install pip
#     easy_install: name=pip state=latest
#     notify: 
#       - restart apache2
#  handlers:
#   - name: restart apache2
#     service: name=apache2 state=restarted 

  
